name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: The version to publish
        type: string
        required: true
      bumpVersion:
        description: Bump the version file and create tag
        type: boolean
        default: false
      playstore:
        description: Release to Play store
        type: boolean
        default: false
      ghRelease:
        description: Create a github release
        type: boolean
        default: false
      draft:
        description: Create a draft release
        type: boolean
        default: false


jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Dependencies
        run: |
          npm i --global conventional-changelog-cli

      - name: Set version number
        working-directory: app/
        run: |
          sed -ri 's|(\s*versionCode\s*=\s*)(.*)|\1'$GITHUB_RUN_NUMBER'|g' build.gradle.kts
          sed -ri 's|(versionName\s*=\s*")(.*)(")|\1'$VERSION'\3|g' build.gradle.kts
        env:
          VERSION: ${{ inputs.version }}

      - name: Edit changelog
        run: .github/scripts/edit-changelog.sh "$VERSION"
        env:
          VERSION: ${{ inputs.version }}

      - name: Commit and tag
        if: ${{ inputs.bumpVersion }}
        run: |
          git config --global user.name "Github Actions [Bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY

          git add ./
          git commit -m "Bump $VERSION"
          git tag "$VERSION"

          git push
          git push --tags
        env:
          VERSION: ${{ inputs.version }}

      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v2
        with:
          changelog_file: CHANGELOG.md
          release_notes_file: release-notes.md

      - name: Create whatsnew file
        run: |
          # remove headings
          sed -r 's/^#+ ([[:alnum:][:blank:]]+)/\1:/g' release-notes.md > whatsnew-en-GB
          # covert * lists to - lists as they're more visually pleasing
          sed -i -r 's/^\* ([[:alnum:]]+)/- \1/g' whatsnew-en-GB
          # strip commit links because they don't render right
          sed -i -r 's/(.*)\(\[[[:alnum:]]+\]\(https.*\)\)/\1/g' whatsnew-en-GB
          # capitalise first letter of each bullet
          sed -i -r 's/(- )([[:alpha:]])(.*)/\1\u\2\3/g' whatsnew-en-GB
          
          echo "Whats new:"
          echo "----------"
          cat whatsnew-en-GB

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-notes
          path: |
            whatsnew-en-GB
            release-notes.md

      - name: Summary
        run: |
          echo "### Version info" >> $GITHUB_STEP_SUMMARY
          echo "Version: $VERSION" >> $GITHUB_STEP_SUMMARY
          echo "Version Code: $GITHUB_RUN_NUMBER" >> $GITHUB_STEP_SUMMARY
          echo "### Release notes" >> $GITHUB_STEP_SUMMARY
          cat release-notes.md >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Whatsnew" >> $GITHUB_STEP_SUMMARY
          cat whatsnew-en-GB >> $GITHUB_STEP_SUMMARY
        env:
          VERSION: ${{ inputs.version }}

  build:
    needs: [bump_version]
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      version: ${{ inputs.bumpVersion == true && inputs.version || null }}
      bumpVersionCode: ${{ inputs.bumpVersion == false }}

  release_github:
    if: ${{ inputs.ghRelease }}
    runs-on: ubuntu-latest
    environment: release-env
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.bumpVersion == true && inputs.version || env.GITHUB_REF_NAME }}

      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: app-build
          path: dist

      - name: Download release notes
        uses: actions/download-artifact@v4
        with:
          name: release-notes
          path: whatsnew

      - name: Publish GitHub release
        uses: softprops/action-gh-release@v2
        with:
          body_path: whatsnew/release-notes.md
          draft: false
          files: dist/*
          name: v${{ inputs.version }}
          tag_name: ${{ inputs.version }}

  # qa == "Internal testing" -- devs only. Not much use
#  qa:
#    needs: [ build ]
#    uses: ./.github/workflows/release-playstore.yml
#    secrets: inherit
#    with:
#      track: qa
#      draft: ${{ inputs.draft }}

  # alpha == "Closed testing" -- testing group
  alpha:
    needs: [ build ]
    uses: ./.github/workflows/release-playstore.yml
    secrets: inherit
    with:
      track: alpha
      draft: ${{ inputs.draft }}

  # beta == "Open testing" -- unused as it requires production
#  beta:
#    needs: [ alpha ]
#    uses: ./.github/workflows/release-playstore.yml
#    secrets: inherit
#    with:
#      track: beta
#      draft: ${{ inputs.draft }}

  production:
    needs: [ alpha ]
    uses: ./.github/workflows/release-playstore.yml
    secrets: inherit
    with:
      track: production
      draft: ${{ inputs.draft }}